app/models/cart.rb, app/models/delivery.rb, app/models/genre.rb, app/models/order.rb, app/models/product.rb, app/models/user.rb
=> [Add]Relations

app/controllers/users_controller.rb
=> users_controller add

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/admin/homes_controller.rb, app/views/admin/homes/top.html.erb
・Admin/Homesコントローラにtopメソッドを追加
・Admin/Homesのビューに「top.html.erb」を追加
・「application.css」を「application.scss」にリネームしbootstrap用の設定を行った
・「application.js」にbootstrap用の設定を行った
=> [Add]AdminHome,Bootstrap

app/controllers/users_controller.rb, app/views/users/edit.html.erb, app/views/users/show.html.erb
=> view_users_edit

app/controllers/application_controller.rb, app/views/admins/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/users/registrations/new.html.erb, db/migrate/20200314121156_devise_create_users.rb, db/migrate/20200314121509_create_genres.rb, db/migrate/20200314121626_create_products.rb, db/schema.rb
・ApplicationControllerにユーザー登録で使える項目を追加
・UserのSignUp画面に項目を追加
・ログイン後のリダイレクト先をAdminとUserで別れるよう変更
・Boolean型の初期値がtrueとなるようDBの設定を変更
=> [Add]Devise_Setting DB_Setting

app/controllers/admin/products_controller.rb, app/controllers/homes_controller.rb, app/models/product.rb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb, app/views/layouts/_admin_header.html.erb, app/views/layouts/_before_login.html.erb, app/views/layouts/_user_header.html.erb, app/views/layouts/application.html.erb, config/initializers/application_controller_renderer.rb
・Admin/Productのindex,show,new,createを大まかに作成しました
・refileを利用するためのkeyを登録しました
・layoutsファイルをrenderで表示できるよう変更しました
・管理者ログイン時に商品の一覧画面へのリンクをヘッダーに追加しました
=> [Add]Products

app/controllers/admin/products_controller.rb, app/helpers/application_helper.rb, app/models/product.rb, app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb, db/migrate/20200314121626_create_products.rb, db/schema.rb
・Admin_productのshow、edit、updateを追加しました。
・Admin_productのindex,show,edit,updateのviewを追加・編集しました
・ApplicationHelperに消費税計算及び金額の「,」が出るようヘルパーを定義しました
=> [Add]admin_product

app/controllers/carts_controller.rb
=> Carts destroy all

app/controllers/deliveries_controller.rb, app/models/delivery.rb, app/views/deliveries/edit.html.erb, app/views/deliveries/index.html.erb
=> [add]delivery

app/controllers/admin/products_controller.rb, app/controllers/carts_controller.rb, app/controllers/products_controller.rb, app/views/carts/index.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb
=> Product index show

app/controllers/orders_controller.rb, app/helpers/application_helper.rb, app/models/delivery.rb, app/models/order.rb, app/models/ordered_product.rb, app/models/user.rb, app/views/orders/complete.html.erb, app/views/orders/index.html.erb, app/views/orders/input.html.erb, app/views/orders/new.html.erb, app/views/orders/show.html.erb, app/views/products/en.yml, app/views/products/ja.yml, config/locales/ja.yml, db/schema.rb, er
- コントローラ内にindex,input,new,create,complete,showメソッドを作成しました
- index,input,new,create,complete,showのviewを作成しました
- リレーションの設定を行いました
- enum・ymlの情報を追記しました。
- enum・ymlの情報を追記しました
- 住所を繋げて表示する必要があったため、display_addressメソッドを作成しました
- 商品の合計金額を計算するために、モデル内でuser_total_priceメソッドを作成しました
=> [Add]user_order

app/controllers/carts_controller.rb, app/views/carts/index.html.erb
=> cart_modified

app/controllers/admin/genres_controller.rb, app/views/admin/genres/index.html.erb, app/views/layouts/_admin_header.html.erb, db/seeds.rb
=> [Fix]Admin/Genre

app/controllers/orders_controller.rb, app/models/cart.rb, app/models/product.rb, app/models/user.rb
- カートモデル内からpriceを削除したため発生していた不具合を修正しました
- カートモデル内から金額を取得するため、消費税計算を行うメソッドを作成しました
=> User order 2nd

app/controllers/users_controller.rb, app/views/layouts/_admin_header.html.erb, app/views/users/edit.html.erb, app/views/users/quit.html.erb, app/views/users/show.html.erb, config/routes.rb, db/schema.rb
=> [add]admin/head quit

app/controllers/admin/ordered_products_controller.rb, app/controllers/admin/orders_controller.rb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/orders/show.html.erb
=> Admin orders

app/assets/stylesheets/orders.scss, app/views/orders/complete.html.erb, app/views/orders/index.html.erb, app/views/orders/input.html.erb, app/views/orders/new.html.erb, db/schema.rb, db/seeds.rb
- Users/Ordersのレイアウトを修正しました
- seedファイルを作成しました
=> [Fix]Orders_layout,[Add]seed

app/assets/stylesheets/application.scss, app/views/admin/users/edit.html.erb, app/views/admins/sessions/new.html.erb, app/views/layouts/_user_header.html.erb, app/views/users/quit.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb, app/views/users/show.html.erb
=> [fix]layout

app/controllers/admin/orders_controller.rb, app/controllers/carts_controller.rb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb
=> Admin order

app/controllers/admin/genres_controller.rb, app/controllers/admin/products_controller.rb, app/models/genre.rb, app/models/product.rb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb, app/views/layouts/_error_messages.html.erb, db/seeds.rb
- Genre及びProductにvalidationを追加しました
- validation追加に伴い、viewとコントローラを追記しました
- seedファイルを変更しました
=> [Add]Genre & Product_Valid

config/locales/ja.yml
- エラー時に出力されるカラム名が日本語で出力されるよう、ymlファイルを追記しました
=> [Add]Translation

app/assets/stylesheets/application.scss, app/views/admins/sessions/new.html.erb, app/views/carts/index.html.erb, app/views/deliveries/index.html.erb, app/views/homes/top.html.erb, app/views/layouts/_before_login.html.erb, app/views/layouts/_user_header.html.erb, app/views/products/show.html.erb, app/views/users/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/show.html.erb
=> [fix]layout2

app/assets/stylesheets/application.scss, app/views/carts/index.html.erb, app/views/products/index.html.erb
=> modified_product_index

app/controllers/admin/ordered_products_controller.rb, app/models/order.rb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, config/routes.rb
=> modified_admin_order_show

app/controllers/admin/genres_controller.rb, app/controllers/admin/products_controller.rb, app/controllers/orders_controller.rb, app/views/admin/genres/index.html.erb, app/views/admin/products/index.html.erb, app/views/orders/index.html.erb
- admin/genre,user/orders,admin/productsのindexにkaminariを実装しました。
=> [Add]Kaminari

app/controllers/admin/genres_controller.rb
- genreを空白で登録した時に発生していたエラーを修正しました。
=> [Fix]genre/kaminari

app/assets/javascripts/admin/product_regist.js, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/admin/products/index.html.erb, app/views/carts/index.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb
=> Modified adimin cart show

app/assets/stylesheets/admin/orders.scss, app/controllers/admin/products_controller.rb, app/models/genre.rb, app/models/product.rb, app/views/admin/products/edit.html.erb, app/views/admin/products/index.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb
- レイアウトを編集しました
- falseで登録を行うとエラーになっていた問題を修正しました
=> [Fix]Admin/Product

app/assets/stylesheets/admin/genres.scss, app/assets/stylesheets/admin/homes.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/orders.scss, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/homes/top.html.erb, app/views/orders/index.html.erb, app/views/orders/input.html.erb, app/views/orders/new.html.erb, app/views/users/edit.html.erb, app/views/users/registrations/new.html.erb
- genres/editのレイアウトを修正しました
- genres/indexのレイアウトを修正しました
- admin/home/topのレイアウトを修正しました
- admin/ordersのレイアウトを修正しました
- ユーザ登録画面のレイアウトを修正しました
- ユーザ情報変更画面のレイアウトを修正しました
=> [Fix]Layouts

app/models/genre.rb, spec/models/admin_spec.rb, spec/models/cart_spec.rb, spec/models/delivery_spec.rb, spec/models/genre_spec.rb, spec/models/order_spec.rb, spec/models/ordered_product_spec.rb, spec/models/product_spec.rb
- 各モデルのRSpecを記述しました。(validationチェックのみ）
=> [Add]RSpec_model

spec/models/order_spec.rb, spec/models/ordered_product_spec.rb
=> [Fix]RSpec

app/assets/stylesheets/application.scss, app/assets/stylesheets/products.scss, app/controllers/products_controller.rb, app/views/layouts/application.html.erb, app/views/products/_genrebox.html.erb, app/views/products/index.html.erb, app/views/products/show.html.erb, app/views/users/show.html.erb
商品関係のレイアウト調整
ユーザー詳細のレイアウト調整
フッター作成、最下部固定
=> [fix]product layout

app/controllers/admin/genres_controller.rb, app/controllers/admin/products_controller.rb, app/controllers/carts_controller.rb, app/controllers/orders_controller.rb, app/controllers/products_controller.rb, app/views/carts/index.html.erb, app/views/orders/new.html.erb
- genres
　登録時にフラッシュメッセージ が出るよう変更
- products
　登録時にフラッシュメッセージが出るよう変更・redirect先を変更
　商品の一覧表示の中に非表示にしているジャンルの商品も表示されてしまう不具合を修正
- cart
　一覧画面に他のユーザのカート情報が出力されてしまう不具合を修正。viewのリンク先を変更
- admin/orders
　カートを削除すると全ユーザのカート情報が削除されてしまう不具合を修正
　画面から住所を入力した場合、deliveriesテーブルにデータが入るよう処理を追加
=> [Fix]Controllers
